/* RxDx design system specimen page */
(function () {
  var r = document.documentElement, I = RX.ICON, q = new URLSearchParams(location.search), ar = r.dir === 'rtl';
  function L(en, a) { return ar ? a : en; }
  var TOK = [['--bg', 'background'], ['--surface', 'surface'], ['--surface-2', 'surface-2'], ['--border', 'border'], ['--border-strong', 'border-strong'], ['--text', 'text'], ['--text-2', 'text-2'], ['--text-3', 'text-3'],
    ['--teal', 'primary teal'], ['--teal-hover', 'teal hover'], ['--teal-tint', 'teal tint'], ['--ink', 'sidebar ink'], ['--ink-2', 'ink-2'], ['--coral', 'brand coral'], ['--info', 'info blue'], ['--gold', 'insurer gold'],
    ['--success', 'success'], ['--warning', 'warning'], ['--error', 'error']];
  function val(v) { return getComputedStyle(r).getPropertyValue(v).trim(); }
  function spec() {
    var C = 2 * Math.PI * 7;
    return '<div class="sys">' +
      '<h2>' + L('Colour', 'الألوان') + '</h2><p>' + L('One teal for action. Coral only for the brand and highlights.', 'تركوازي واحد للفعل. المرجاني للعلامة والتمييز فقط.') + '</p><div class="grid">' +
      TOK.map(function (t) { return '<div class="sw"><i style="background:var(' + t[0] + ')"></i><b>' + t[1] + '</b><code>' + val(t[0]) + '</code></div>'; }).join('') + '</div>' +
      '<h2>' + L('Type', 'الخط') + '</h2><p>IBM Plex Sans Arabic · JetBrains Mono</p><div class="spec">' +
      [['36', 'var(--fs-36)', 700], ['28', 'var(--fs-28)', 700], ['20', 'var(--fs-20)', 600], ['17', 'var(--fs-17)', 500], ['15', 'var(--fs-15)', 400], ['13.5', 'var(--fs-13)', 400], ['12', 'var(--fs-12)', 500]].map(function (s) {
        return '<div class="ts"><code>' + s[0] + 'px</code><span style="font:' + s[2] + ' ' + s[1] + '/1.3 var(--sans)">' + L('Codes you can defend', 'أكواد تستطيع الدفاع عنها') + '</span></div>'; }).join('') +
      '<div class="ts"><code>mono</code><span class="code" style="font-size:28px">M54.12 · E11.9 · I10</span></div><div class="ts"><code>micro</code><span class="micro" lang="en">Clinical note</span></div></div>' +
      '<h2>' + L('Buttons', 'الأزرار') + '</h2><div class="spec row"><button class="btn btn-primary">' + L('Analyze', 'حلّل') + '<span class="kbd">⌘↵</span></button><button class="btn btn-secondary">' + I('copy') + L('Copy codes', 'نسخ الأكواد') + '</button><button class="btn btn-ghost">' + I('edit') + L('Edit', 'تعديل') + '</button><button class="btn btn-danger">' + I('x') + L('Reject', 'رفض') + '</button><button class="btn btn-primary" disabled>' + L('Disabled', 'معطل') + '</button><button class="btn btn-secondary btn-sm">' + L('Small', 'صغير') + '</button></div>' +
      '<h2>' + L('Inputs', 'الحقول') + '</h2><div class="spec"><div class="row" style="align-items:flex-end"><div class="field"><label>' + L('Age', 'العمر') + '</label><input class="input num" value="55"></div><div class="field" style="flex:1;min-width:220px"><label>' + L('Reason', 'السبب') + '</label><input class="input" placeholder="' + L('One line', 'سطر واحد') + '"></div>' +
      '<div class="field"><span class="label">' + L('Encounter', 'نوع الزيارة') + '</span><div class="seg"><button aria-pressed="true">' + L('Outpatient', 'عيادة') + '</button><button>' + L('Emergency', 'طوارئ') + '</button><button>' + L('Inpatient', 'تنويم') + '</button></div></div></div>' +
      '<label class="search" style="margin-top:18px">' + I('search') + '<input placeholder="' + L('Search a diagnosis or code', 'ابحث عن تشخيص أو كود') + '"><span class="count">16,953 codes · 1,548 drugs</span></label>' +
      '<div class="tabs" style="margin-top:18px"><button aria-selected="true">' + L('Overview', 'نظرة عامة') + '</button><button>' + L('Revenue at risk', 'إيرادات معرّضة للخطر') + '</button><button>' + L('Documentation quality', 'جودة التوثيق') + '</button></div></div>' +
      '<h2>' + L('Codes, status, evidence', 'الأكواد والحالة والدليل') + '</h2><div class="spec"><div class="row"><span class="cchip is-principal">M54.12</span><span class="cchip">E11.9</span><span class="cchip">I10</span>' +
      '<span class="badge ok">' + I('check') + L('Confirmed', 'مؤكد') + '</span><span class="badge warn">' + I('alert') + L('Check', 'راجِع') + '</span><span class="badge err">' + I('x') + L('Rejected', 'مرفوض') + '</span><span class="badge info">' + I('info') + L('Family history', 'تاريخ عائلي') + '</span><span class="badge gold">' + I('flag') + L('3 open items', '3 بنود مفتوحة') + '</span>' +
      ['high', 'check', 'low'].map(function (l, i) { var f = [.9, .58, .3][i]; return '<span class="conf ' + l + '"><svg viewBox="0 0 18 18"><circle class="trk" cx="9" cy="9" r="7"/><circle class="val" cx="9" cy="9" r="7" stroke-dasharray="' + C.toFixed(2) + '" stroke-dashoffset="' + (C * (1 - f)).toFixed(2) + '"/></svg>' + L(['High', 'Check', 'Low'][i], ['عالية', 'راجِع', 'منخفضة'][i]) + (i === 0 ? ' <span class="pct">94%</span>' : '') + '</span>'; }).join('') +
      '<span class="ins bupa">Bupa</span><span class="ins taw">Tawuniya</span><span class="ins art">Al Rajhi</span></div>' +
      '<p class="clin" style="margin:18px 0 0;font-size:15.5px;line-height:1.7">55-year-old woman with <mark class="ev is-on">neck pain radiating to the left arm</mark>. <mark class="nc">No trauma</mark>. Examination: <mark class="ev">reduced left biceps reflex</mark>, <mark class="nc int">numbness in the left thumb</mark>.</p>' +
      '<div class="row" style="margin-top:12px"><button class="quote clin">“Assessment: cervical radiculopathy”</button><span class="tag">' + L('Treatment', 'العلاج') + '</span><span class="tag">' + L('Monitoring', 'المتابعة') + '</span></div></div>' +
      '<h2>' + L('Diagnosis cards', 'بطاقات التشخيص') + '</h2><div class="spec" style="display:grid;gap:12px"><article class="card dx dx-principal is-sel"><div class="dx-row"><div class="dx-code">M54.12</div><div class="dx-badges"><span class="badge ok">' + I('check') + L('Confirmed', 'مؤكد') + '</span></div></div><div class="dx-desc clin">Radiculopathy, cervical region</div></article>' +
      '<article class="card dx dx-add open"><div class="dx-sum" style="display:flex;align-items:center;gap:14px;padding:14px 18px"><span class="dx-code">E11.9</span><span class="d clin">Type 2 diabetes mellitus without complication</span>' + I('chev', 'chev') + '</div><div class="dx-more"><div><div class="in"><dl class="kv"><dt>' + L('Supports', 'يدعم') + '</dt><dd class="clin">HbA1c, metformin</dd></dl></div></div></div></article></div>' +
      '<h2>' + L('Feedback', 'التنبيهات') + '</h2><div class="spec" style="display:grid;gap:10px"><div class="alert info">' + I('info') + '<div>' + L('The note changed. Analyze again to update the result.', 'تغيّرت الملاحظة. حلّل من جديد لتحديث النتيجة.') + '</div></div>' +
      '<div class="alert warn">' + I('cloud') + '<div><b>' + L('Online coding service is on.', 'خدمة الترميز عبر الإنترنت مفعّلة.') + '</b> ' + L('The note text is sent to the server.', 'يُرسل نص الملاحظة إلى الخادم.') + '</div></div>' +
      '<div class="alert ok">' + I('check') + '<div>' + L('All six validation checks passed.', 'اجتازت الملاحظة فحوص التحقق الستة.') + '</div></div><div class="alert err">' + I('alert') + '<div>' + L('No diagnosis was found. Check that the assessment is written.', 'لم يُعثر على تشخيص. تأكد من كتابة التقييم.') + '</div></div>' +
      '<div class="row"><div class="toast" style="animation:none">' + I('check') + L('Codes copied · M54.12, E11.9, I10', 'نُسخت الأكواد') + '</div><button class="btn btn-secondary" data-tip="' + L('Copy codes  C', 'نسخ الأكواد  C') + '">' + L('Hover for tooltip', 'مرّر للتلميح') + '</button></div></div>' +
      '<h2>' + L('Dialog and dropdown', 'الحوار والقائمة') + '</h2><div class="spec row" style="align-items:flex-start"><div class="dialog" style="animation:none"><header><h2>' + L('Finalise with open items', 'اعتماد مع بنود مفتوحة') + '</h2></header><div class="body"><p style="margin:0 0 12px">' + L('2 documentation gaps and 4 insurer items are still open.', 'بقيت نقصان في التوثيق و4 بنود للتأمين.') + '</p><div class="field"><label>' + L('Reason', 'السبب') + '</label><input class="input"></div></div><footer><button class="btn btn-secondary">' + L('Cancel', 'إلغاء') + '</button><button class="btn btn-primary">' + L('Finalise', 'اعتماد') + '</button></footer></div>' +
      '<div class="menu" style="position:static;animation:none"><button>' + I('braces') + 'FHIR R4 JSON</button><button>' + I('doc') + 'CSV</button><hr><button>' + I('send') + L('Send to coder review', 'إرسال لمراجعة المرمِّز') + '</button></div></div>' +
      '<h2>' + L('Progress', 'التقدّم') + '</h2><div class="spec"><div class="steps"><button class="step done"><span class="n">✓</span>' + L('History', 'التاريخ') + '</button><button class="step cur"><span class="n">3</span>' + L('Red flags', 'علامات الخطر') + '</button><button class="step"><span class="n">4</span>' + L('Background', 'الخلفية') + '</button><button class="step leave"><span class="n">5</span>' + L('Before leaving', 'قبل المغادرة') + '</button></div>' +
      '<div class="rail" style="margin-top:22px"><div class="rail-track"><div class="rail-fill" style="width:50%"></div></div><div class="rail-steps">' + [L('Reading', 'القراءة'), L('Finding', 'الإيجاد'), L('Setting aside', 'الاستبعاد'), L('Principal', 'الرئيسي'), L('Matching', 'المطابقة'), L('Validating', 'التحقق')].map(function (s, i) { return '<span class="' + (i < 3 ? 'done' : i === 3 ? 'on' : '') + '">' + s + '</span>'; }).join('') + '</div></div></div>' +
      '<h2>' + L('Table', 'الجدول') + '</h2><div class="card" style="overflow:hidden"><table class="tbl"><thead><tr><th>' + L('Service', 'الخدمة') + '</th><th>Bupa</th><th>Tawuniya</th><th>Al Rajhi</th></tr></thead><tbody><tr><td class="clin">Physiotherapy sessions</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td class="clin">MRI</td><td>✓</td><td>—</td><td>✓</td></tr></tbody></table></div>' +
      '<h2>' + L('Loading, empty, error', 'التحميل والفراغ والخطأ') + '</h2><div class="spec" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px"><div class="card" style="padding:18px"><div class="skel" style="height:30px;width:45%"></div><div class="skel" style="height:14px;width:80%;margin-top:12px"></div><div class="skel" style="height:14px;width:60%;margin-top:8px"></div></div>' +
      '<div class="card"><div class="empty" style="padding:28px"><span class="ic">' + I('note') + '</span><h3>' + L('Start with the note', 'ابدأ بالملاحظة') + '</h3></div></div><div class="card"><div class="empty" style="padding:28px"><span class="ic err">' + I('alert') + '</span><h3>' + L('No diagnosis was found.', 'لم يُعثر على تشخيص.') + '</h3></div></div></div>' +
      '<h2>' + L('Shape and depth', 'الشكل والعمق') + '</h2><div class="spec row">' + [['10', 'input'], ['14', 'card'], ['16', 'field · dialog'], ['999', 'chip']].map(function (x) { return '<div style="width:130px;height:84px;border-radius:' + Math.min(+x[0], 42) + 'px;background:var(--paper);border:1px solid var(--border);box-shadow:var(--shadow);display:grid;place-items:center;font:500 11.5px/1.3 var(--mono);color:var(--text-2);text-align:center">' + x[0] + '<br>' + x[1] + '</div>'; }).join('') + '</div></div>';
  }
  var out = document.getElementById('out'), mode = q.get('mode') || 'single';
  function render() {
    if (mode === 'quad' && !q.get('embed')) {
      out.innerHTML = '<div class="quad">' + [['light', 'ltr'], ['dark', 'ltr'], ['light', 'rtl'], ['dark', 'rtl']].map(function (v) {
        return '<figure style="margin:0"><figcaption>' + v[0].toUpperCase() + ' · ' + v[1].toUpperCase() + '</figcaption><iframe loading="lazy" title="' + v.join(' ') + '" src="system.html?embed=1&theme=' + v[0] + '&dir=' + v[1] + '"></iframe></figure>'; }).join('') + '</div>';
    } else out.innerHTML = spec();
    document.querySelectorAll('#mode button').forEach(function (b) { b.setAttribute('aria-pressed', b.dataset.m === mode); });
  }
  function nav(k, v) { q.set(k, v); location.search = q.toString(); }
  document.getElementById('mode').onclick = function (e) { var b = e.target.closest('button'); if (b) nav('mode', b.dataset.m); };
  document.getElementById('dir').onclick = function () { nav('dir', r.dir === 'rtl' ? 'ltr' : 'rtl'); };
  document.getElementById('thm').onclick = function () { nav('theme', r.dataset.theme === 'dark' ? 'light' : 'dark'); };
  document.getElementById('dir').textContent = r.dir === 'rtl' ? 'LTR' : 'RTL';
  document.getElementById('thm').textContent = r.dataset.theme === 'dark' ? 'Light' : 'Dark';
  render();
})();
